# Projeto FIAP Fase 4

## Get Database

In [1]:
import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt
import datetime
import pandas as pd
import os
import sys

In [69]:
list_symbol = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']

start_date = '2002-01-01'
end_date = '2026-04-20'

In [70]:
df = yf.download(list_symbol, start=start_date, end=end_date)

df_index_ajusted = df.stack(level=1).reset_index()

df_index_ajusted

[*********************100%***********************]  5 of 5 completed
/var/folders/h0/9cxt3flx6px_mz8j5myq3cjw0000gn/T/ipykernel_13700/296897865.py:3: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_index_ajusted = df.stack(level=1).reset_index()

Price,Date,Ticker,Close,High,Low,Open,Volume
0,2002-01-02,AAPL,0.349069,0.349069,0.328994,0.330342,529496800.0
1,2002-01-02,AMZN,0.548000,0.550000,0.524000,0.546500,130392000.0
2,2002-01-02,MSFT,20.429262,20.450593,19.963022,20.310417,48124000.0
3,2002-01-03,AAPL,0.353264,0.355811,0.341129,0.344574,612007200.0
4,2002-01-03,AMZN,0.595000,0.597000,0.552500,0.556500,217514000.0
...,...,...,...,...,...,...,...
27279,2026-04-17,AAPL,270.230011,272.299988,266.720001,266.959991,61436200.0
27280,2026-04-17,AMZN,250.559998,256.179993,250.110001,254.990005,52029300.0
27281,2026-04-17,GOOGL,341.679993,342.320007,336.239990,337.649994,25581900.0
27282,2026-04-17,META,688.549988,691.520020,675.130005,678.599976,16283500.0
27283,2026-04-17,MSFT,422.790009,431.579987,420.690002,424.820007,48568200.0

In [71]:
df_index_ajusted.describe()

Price,Date,Close,High,Low,Open,Volume
count,27284,27284.000000,27284.000000,27284.000000,27284.000000,2.728400e+04
mean,2015-01-25 19:11:11.866295296,90.344040,91.331769,89.298839,90.326663,1.425267e+08
min,2002-01-02 00:00:00,0.196558,0.197606,0.190565,0.194610,4.726100e+06
25%,2009-06-08 00:00:00,13.313077,13.476463,13.167226,13.328280,3.213912e+07
50%,2015-06-11 00:00:00,33.434975,33.779584,33.142955,33.426264,6.334415e+07
75%,2020-11-09 00:00:00,135.719006,137.238734,134.173932,135.721226,1.370256e+08
max,2026-04-17 00:00:00,788.148987,794.384398,778.990557,789.296390,3.372970e+09
std,NaN,122.617898,123.982809,121.197709,122.638057,2.316138e+08

In [72]:
df_index_ajusted.isna().sum()

Price
Date      0
Ticker    0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [73]:
df_index_ajusted.dtypes

Price
Date      datetime64[ns]
Ticker            object
Close            float64
High             float64
Low              float64
Open             float64
Volume           float64
dtype: object

In [74]:
import sqlite3

In [75]:
# ensure the database directory exists before connecting
db_dir = "./src/database"
os.makedirs(db_dir, exist_ok=True)

In [76]:
db_path = os.path.abspath(os.path.join(db_dir, "bronze.db"))

In [77]:
db_path

'/Users/viniciussouza/Codes/FIAP/FIAP_projeto_fase_4/src/notebooks/src/database/bronze.db'

In [78]:
conn = sqlite3.connect(db_path)
conn

In [79]:
df_index_ajusted.to_sql("stocks_raw", conn, if_exists="replace", index=False)

27284

In [80]:
conn.close()

## Novas datas para teste do modelo na API

In [7]:
list_symbol = ['AAPL']

start_date = '2026-01-21'
end_date = '2026-05-03'

In [10]:
df = yf.download(list_symbol, start=start_date, end=end_date)

df_index_ajusted = df.stack(level=1).reset_index()


df_index_ajusted.columns = [
    "date", "ticker", "open", "high", "low", "close", "volume"
]

df_index_ajusted.sort_values(by=["date"],inplace=True)

df_index_ajusted

[*********************100%***********************]  1 of 1 completed
/var/folders/h0/9cxt3flx6px_mz8j5myq3cjw0000gn/T/ipykernel_81799/353904856.py:3: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_index_ajusted = df.stack(level=1).reset_index()

         date ticker        open        high         low       close    volume
0  2026-01-21   AAPL  247.418488  251.324836  244.950795  248.467509  54641700
1  2026-01-22   AAPL  248.117844  250.765360  247.918018  248.967040  39708300
2  2026-01-23   AAPL  247.808121  249.176850  244.451261  247.088808  41689000
3  2026-01-26   AAPL  255.171234  256.320153  249.566478  251.244900  55969200
4  2026-01-27   AAPL  258.028534  261.705117  257.968592  258.927717  49648300
..        ...    ...         ...         ...         ...         ...       ...
66 2026-04-27   AAPL  267.609985  268.359985  265.070007  266.089996  41466800
67 2026-04-28   AAPL  270.709991  273.230011  268.660004  272.339996  40018900
68 2026-04-29   AAPL  270.170013  271.040009  267.040009  267.549988  30047900
69 2026-04-30   AAPL  271.350006  276.000000  268.140015  270.500000  91848200
70 2026-05-01   AAPL  280.140015  287.220001  278.369995  278.859985  79844600

[71 rows x 7 columns]

In [11]:
result = (
    df_index_ajusted
    .groupby("ticker")
    .apply(lambda x: {
        "ticker": x["ticker"].iloc[0],
        "history": x[["open", "high", "low", "close", "volume"]]
        .to_dict(orient="records")
    })
    .tolist()
)

import json

print(json.dumps(result, indent=2))

[
  {
    "ticker": "AAPL",
    "history": [
      {
        "open": 247.41848754882812,
        "high": 251.3248360900433,
        "low": 244.9507953165175,
        "close": 248.46750904444812,
        "volume": 54641700
      },
      {
        "open": 248.1178436279297,
        "high": 250.76536025794266,
        "low": 247.9180183962477,
        "close": 248.96703988447874,
        "volume": 39708300
      },
      {
        "open": 247.80812072753906,
        "high": 249.17685039145397,
        "low": 244.45126111041233,
        "close": 247.08880782235642,
        "volume": 41689000
      },
      {
        "open": 255.17123413085938,
        "high": 256.32015295784896,
        "low": 249.5664780183616,
        "close": 251.24490015634893,
        "volume": 55969200
      },
      {
        "open": 258.0285339355469,
        "high": 261.70511669708895,
        "low": 257.96859246831417,
        "close": 258.92771692213245,
        "volume": 49648300
      },
      {
        "open": 256.2002868652344,
        "high": 258.61800761819165,
        "low": 254.27208306792676,
        "close": 257.409147241713,
        "volume": 41288000
      },
      {
        "open": 258.0385437011719,
        "high": 259.4072580677027,
        "low": 254.17216647920577,
        "close": 257.75880668092503,
        "volume": 67253000
      },
      {
        "open": 259.2374267578125,
        "high": 261.6551472598355,
        "low": 251.94423313215475,
        "close": 254.93144331105526,
        "volume": 92443400
      },
      {
        "open": 269.7575988769531,
        "high": 270.2371306501278,
        "low": 258.9676766447768,
        "close": 259.7869174093499,
        "volume": 73913400
      },
      {
        "open": 269.22808837890625,
        "high": 271.6258386480508,
        "low": 267.3598109321867,
        "close": 268.9483513556569,
        "volume": 64394700
      },
      {
        "open": 276.23150634765625,
        "high": 278.68922850453845,
        "low": 272.03545112075,
        "close": 272.03545112075,
        "volume": 90545700
      },
      {
        "open": 275.6520690917969,
        "high": 279.2387093202658,
        "low": 272.97458180817284,
        "close": 277.86999494352693,
        "volume": 52977400
      },
      {
        "open": 277.8599853515625,
        "high": 280.6473855638201,
        "low": 276.67109542368036,
        "close": 276.8609202349588,
        "volume": 50453400
      },
      {
        "open": 274.6199951171875,
        "high": 278.20001220703125,
        "low": 271.70001220703125,
        "close": 277.9100036621094,
        "volume": 44623400
      },
      {
        "open": 273.67999267578125,
        "high": 275.3699951171875,
        "low": 272.94000244140625,
        "close": 274.8900146484375,
        "volume": 34376900
      },
      {
        "open": 275.5,
        "high": 280.17999267578125,
        "low": 274.45001220703125,
        "close": 274.70001220703125,
        "volume": 51931300
      },
      {
        "open": 261.7300109863281,
        "high": 275.7200012207031,
        "low": 260.17999267578125,
        "close": 275.5899963378906,
        "volume": 81077200
      },
      {
        "open": 255.77999877929688,
        "high": 262.2300109863281,
        "low": 255.4499969482422,
        "close": 262.010009765625,
        "volume": 56290700
      },
      {
        "open": 263.8800048828125,
        "high": 266.2900085449219,
        "low": 255.5399932861328,
        "close": 258.04998779296875,
        "volume": 58469100
      },
      {
        "open": 264.3500061035156,
        "high": 266.82000732421875,
        "low": 262.45001220703125,
        "close": 263.6000061035156,
        "volume": 34203300
      },
      {
        "open": 260.5799865722656,
        "high": 264.4800109863281,
        "low": 260.04998779296875,
        "close": 262.6000061035156,
        "volume": 30845300
      },
      {
        "open": 264.5799865722656,
        "high": 264.75,
        "low": 258.1600036621094,
        "close": 258.9700012207031,
        "volume": 42070500
      },
      {
        "open": 266.17999267578125,
        "high": 269.42999267578125,
        "low": 263.3800048828125,
        "close": 263.489990234375,
        "volume": 37308200
      },
      {
        "open": 272.1400146484375,
        "high": 274.8900146484375,
        "low": 267.7099914550781,
        "close": 267.8599853515625,
        "volume": 47014600
      },
      {
        "open": 274.2300109863281,
        "high": 274.94000244140625,
        "low": 271.04998779296875,
        "close": 271.7799987792969,
        "volume": 33714300
      },
      {
        "open": 272.95001220703125,
        "high": 276.1099853515625,
        "low": 270.79998779296875,
        "close": 274.95001220703125,
        "volume": 32345100
      },
      {
        "open": 264.17999267578125,
        "high": 272.80999755859375,
        "low": 262.8900146484375,
        "close": 272.80999755859375,
        "volume": 72366500
      },
      {
        "open": 264.7200012207031,
        "high": 266.5299987792969,
        "low": 260.20001220703125,
        "close": 262.4100036621094,
        "volume": 41827900
      },
      {
        "open": 263.75,
        "high": 265.55999755859375,
        "low": 260.1300048828125,
        "close": 263.4800109863281,
        "volume": 38568900
      },
      {
        "open": 262.5199890136719,
        "high": 266.1499938964844,
        "low": 261.4200134277344,
        "close": 264.6499938964844,
        "volume": 39803100
      },
      {
        "open": 260.2900085449219,
        "high": 261.55999755859375,
        "low": 257.25,
        "close": 260.7900085449219,
        "volume": 49658600
      },
      {
        "open": 257.4599914550781,
        "high": 258.7699890136719,
        "low": 254.3699951171875,
        "close": 258.6300048828125,
        "volume": 41120000
      },
      {
        "open": 259.8800048828125,
        "high": 261.1499938964844,
        "low": 253.67999267578125,
        "close": 255.69000244140625,
        "volume": 38218500
      },
      {
        "open": 260.8299865722656,
        "high": 262.4800109863281,
        "low": 256.95001220703125,
        "close": 257.6499938964844,
        "volume": 30590800
      },
      {
        "open": 260.80999755859375,
        "high": 262.1300048828125,
        "low": 259.54998779296875,
        "close": 261.0899963378906,
        "volume": 26218900
      },
      {
        "open": 255.75999450683594,
        "high": 258.95001220703125,
        "low": 254.17999267578125,
        "close": 258.6600036621094,
        "volume": 40794000
      },
      {
        "open": 250.1199951171875,
        "high": 256.3299865722656,
        "low": 249.52000427246094,
        "close": 255.47999572753906,
        "volume": 36930000
      },
      {
        "open": 252.82000732421875,
        "high": 253.88999938964844,
        "low": 249.8800048828125,
        "close": 252.11000061035156,
        "volume": 32074200
      },
      {
        "open": 254.22999572753906,
        "high": 255.1300048828125,
        "low": 252.17999267578125,
        "close": 252.9600067138672,
        "volume": 32361600
      },
      {
        "open": 249.94000244140625,
        "high": 254.94000244140625,
        "low": 249.0,
        "close": 252.6300048828125,
        "volume": 35757900
      },
      {
        "open": 248.9600067138672,
        "high": 251.8300018310547,
        "low": 247.3000030517578,
        "close": 249.39999389648438,
        "volume": 34864100
      },
      {
        "open": 247.99000549316406,
        "high": 249.1999969482422,
        "low": 246.0,
        "close": 247.97999572753906,
        "volume": 88331100
      },
      {
        "open": 251.49000549316406,
        "high": 254.60000610351562,
        "low": 250.27999877929688,
        "close": 253.97000122070312,
        "volume": 40546100
      },
      {
        "open": 251.63999938964844,
        "high": 254.8300018310547,
        "low": 249.5500030517578,
        "close": 250.35000610351562,
        "volume": 45152300
      },
      {
        "open": 252.6199951171875,
        "high": 255.0,
        "low": 251.60000610351562,
        "close": 254.10000610351562,
        "volume": 28476700
      },
      {
        "open": 252.88999938964844,
        "high": 257.0,
        "low": 250.77000427246094,
        "close": 252.1199951171875,
        "volume": 41796700
      },
      {
        "open": 248.8000030517578,
        "high": 255.49000549316406,
        "low": 248.07000732421875,
        "close": 253.89999389648438,
        "volume": 47900000
      },
      {
        "open": 246.6300048828125,
        "high": 250.8699951171875,
        "low": 245.50999450683594,
        "close": 250.07000732421875,
        "volume": 39446200
      },
      {
        "open": 253.7899932861328,
        "high": 255.47999572753906,
        "low": 247.10000610351562,
        "close": 247.91000366210938,
        "volume": 49598100
      },
      {
        "open": 255.6300048828125,
        "high": 256.17999267578125,
        "low": 253.3300018310547,
        "close": 254.0800018310547,
        "volume": 40059400
      },
      {
        "open": 255.9199981689453,
        "high": 256.1300048828125,
        "low": 250.64999389648438,
        "close": 254.1999969482422,
        "volume": 31289400
      },
      {
        "open": 258.8599853515625,
        "high": 262.1600036621094,
        "low": 256.4599914550781,
        "close": 256.510009765625,
        "volume": 29329900
      },
      {
        "open": 253.5,
        "high": 256.20001220703125,
        "low": 245.6999969482422,
        "close": 256.1600036621094,
        "volume": 62148000
      },
      {
        "open": 258.8999938964844,
        "high": 259.75,
        "low": 256.5299987792969,
        "close": 258.45001220703125,
        "volume": 41032800
      },
      {
        "open": 260.489990234375,
        "high": 261.1199951171875,
        "low": 256.07000732421875,
        "close": 259.0,
        "volume": 28121600
      },
      {
        "open": 260.4800109863281,
        "high": 262.19000244140625,
        "low": 259.0199890136719,
        "close": 259.9800109863281,
        "volume": 31291500
      },
      {
        "open": 259.20001220703125,
        "high": 260.17999267578125,
        "low": 256.6600036621094,
        "close": 259.7300109863281,
        "volume": 36234700
      },
      {
        "open": 258.8299865722656,
        "high": 261.92999267578125,
        "low": 257.19000244140625,
        "close": 259.25,
        "volume": 48370700
      },
      {
        "open": 266.42999267578125,
        "high": 266.55999755859375,
        "low": 257.80999755859375,
        "close": 258.1600036621094,
        "volume": 49913500
      },
      {
        "open": 263.3999938964844,
        "high": 267.1600036621094,
        "low": 261.2699890136719,
        "close": 266.79998779296875,
        "volume": 43323100
      },
      {
        "open": 270.2300109863281,
        "high": 272.29998779296875,
        "low": 266.7200012207031,
        "close": 266.9599914550781,
        "volume": 61436200
      },
      {
        "open": 273.04998779296875,
        "high": 274.2799987792969,
        "low": 270.2900085449219,
        "close": 270.3299865722656,
        "volume": 36590200
      },
      {
        "open": 266.1700134277344,
        "high": 272.79998779296875,
        "low": 265.3999938964844,
        "close": 271.5,
        "volume": 50209800
      },
      {
        "open": 273.1700134277344,
        "high": 273.739990234375,
        "low": 266.8699951171875,
        "close": 267.82000732421875,
        "volume": 43249200
      },
      {
        "open": 273.42999267578125,
        "high": 275.7699890136719,
        "low": 271.6499938964844,
        "close": 275.04998779296875,
        "volume": 33399600
      },
      {
        "open": 271.05999755859375,
        "high": 273.05999755859375,
        "low": 269.6499938964844,
        "close": 272.760009765625,
        "volume": 38157100
      },
      {
        "open": 267.6099853515625,
        "high": 268.3599853515625,
        "low": 265.07000732421875,
        "close": 266.0899963378906,
        "volume": 41466800
      },
      {
        "open": 270.7099914550781,
        "high": 273.2300109863281,
        "low": 268.6600036621094,
        "close": 272.3399963378906,
        "volume": 40018900
      },
      {
        "open": 270.1700134277344,
        "high": 271.0400085449219,
        "low": 267.0400085449219,
        "close": 267.54998779296875,
        "volume": 30047900
      },
      {
        "open": 271.3500061035156,
        "high": 276.0,
        "low": 268.1400146484375,
        "close": 270.5,
        "volume": 91848200
      },
      {
        "open": 280.1400146484375,
        "high": 287.2200012207031,
        "low": 278.3699951171875,
        "close": 278.8599853515625,
        "volume": 79844600
      }
    ]
  }
]

/var/folders/h0/9cxt3flx6px_mz8j5myq3cjw0000gn/T/ipykernel_81799/600281735.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: {